/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_ArenaElevatorAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_ArenaElevatorAddonDeed();
			}
		}

		[ Constructable ]
		public AG_ArenaElevatorAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, -1, 5 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, 0, 5 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, 1, 5 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, -1, 5 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, 0, 5 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, 1, 5 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, -1, 5 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, 0, 5 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, 1, 5 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, -1, 10 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, 0, 10 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, 1, 10 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, -1, 10 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, 0, 10 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, 1, 10 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, -1, 10 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, 0, 10 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, 1, 10 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, -1, 15 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, 0, 15 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, 1, 15 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, -1, 15 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, 0, 15 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, 1, 15 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, -1, 15 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, 0, 15 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, 1, 15 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, -1, 20 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, 0, 20 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, 1, 20 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, -1, 20 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, 0, 20 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, 1, 20 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, -1, 20 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, 0, 20 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, 1, 20 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, -1, 25 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, 0, 25 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, 1, 25 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, -1, 25 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, 0, 25 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, 1, 25 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, -1, 25 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, 0, 25 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, 1, 25 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, -1, 30 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, 0, 30 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, 1, 30 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, -1, 30 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, 0, 30 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, 1, 30 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, -1, 30 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, 0, 30 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, 1, 30 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, -1, 35 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, 0, 35 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, -1, 1, 35 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, -1, 35 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, 0, 35 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 0, 1, 35 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, -1, 35 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, 0, 35 );
			ac = new AddonComponent( 1900 );
			ac.Hue = 2797;
			AddComponent( ac, 1, 1, 35 );
			ac = new AddonComponent( 1314 );
			AddComponent( ac, -1, -1, 40 );
			ac = new AddonComponent( 1314 );
			AddComponent( ac, 0, -1, 40 );
			ac = new AddonComponent( 1314 );
			AddComponent( ac, 1, -1, 40 );
			ac = new AddonComponent( 1314 );
			AddComponent( ac, 1, 0, 40 );
			ac = new AddonComponent( 1314 );
			AddComponent( ac, 1, 1, 40 );
			ac = new AddonComponent( 1314 );
			AddComponent( ac, 0, 0, 40 );
			ac = new AddonComponent( 1314 );
			AddComponent( ac, 0, 1, 40 );
			ac = new AddonComponent( 1314 );
			AddComponent( ac, -1, 0, 40 );
			ac = new AddonComponent( 1314 );
			AddComponent( ac, -1, 1, 40 );

		}

		public AG_ArenaElevatorAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_ArenaElevatorAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_ArenaElevatorAddon();
			}
		}

		[Constructable]
		public AG_ArenaElevatorAddonDeed()
		{
			Name = "AG_ArenaElevator";
		}

		public AG_ArenaElevatorAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}
