/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
    public class AG_LargeBrownCarpetAddon : BaseAddon, IDyable
	{
        public virtual bool Dye( Mobile from, DyeTub sender )
        {
            return true;
        }

		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_LargeBrownCarpetAddonDeed();
			}
		}

		[ Constructable ]
		public AG_LargeBrownCarpetAddon( int hue )
		{
			AddonComponent ac;
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 2788 );
			ac.Hue = hue;
			AddComponent( ac, -3, -3, 0 );
			ac = new AddonComponent( 2789 );
			ac.Hue = hue;
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 2791 );
			ac.Hue = hue;
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 2791 );
			ac.Hue = hue;
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 2791 );
			ac.Hue = hue;
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 2791 );
			ac.Hue = hue;
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 2791 );
			ac.Hue = hue;
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 2792 );
			ac.Hue = hue;
			AddComponent( ac, -2, -3, 0 );
			ac = new AddonComponent( 2792 );
			ac.Hue = hue;
			AddComponent( ac, -1, -3, 0 );
			ac = new AddonComponent( 2792 );
			ac.Hue = hue;
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 2792 );
			ac.Hue = hue;
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 2794 );
			ac.Hue = hue;
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 2794 );
			ac.Hue = hue;
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 2794 );
			ac.Hue = hue;
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 2794 );
			ac.Hue = hue;
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 2795 );
			ac.Hue = hue;
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 2787 );
			ac.Hue = hue;
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 2790 );
			ac.Hue = hue;
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 2792 );
			ac.Hue = hue;
			AddComponent( ac, 2, -3, 0 );
			ac = new AddonComponent( 2793 );
			ac.Hue = hue;
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 2793 );
			ac.Hue = hue;
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 2793 );
			ac.Hue = hue;
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 2793 );
			ac.Hue = hue;
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 2793 );
			ac.Hue = hue;
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 2794 );
			ac.Hue = hue;
			AddComponent( ac, 2, 3, 0 );

		}

		public AG_LargeBrownCarpetAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_LargeBrownCarpetAddonDeed : BaseAddonDeed, IDyable
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_LargeBrownCarpetAddon( this.Hue );
			}
		}
		
		public virtual bool Dye( Mobile from, DyeTub sender )
		{
			if ( Deleted )
				return false;
			else if ( RootParent is Mobile && from != RootParent )
				return false;

			Hue = sender.DyedHue;

			return true;
		}

		[Constructable]
		public AG_LargeBrownCarpetAddonDeed()
		{
			Name = "Large Brown Carpet Deed";
		}

		public AG_LargeBrownCarpetAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}
