/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_Nest3Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_Nest3AddonDeed();
			}
		}

		[ Constructable ]
		public AG_Nest3Addon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 7048 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 7045 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 7043 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 7042 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 7046 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 7047 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 7049 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 7050 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 7052 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 7053 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 7059 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 7063 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 7066 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 7067 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 7056 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 7055 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 7056 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 7057 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 7057 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 7051 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 7051 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 7050 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 7048 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 7063 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 7063 );
			AddComponent( ac, -1, 0, 0 );

		}

		public AG_Nest3Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_Nest3AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_Nest3Addon();
			}
		}

		[Constructable]
		public AG_Nest3AddonDeed()
		{
			Name = "AG_Nest3";
		}

		public AG_Nest3AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}
