/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_RivergatesGateAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_RivergatesGateAddonDeed();
			}
		}

		[ Constructable ]
		public AG_RivergatesGateAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 1995 );
			AddComponent( ac, -5, 3, 0 );
			ac = new AddonComponent( 1995 );
			AddComponent( ac, -5, -2, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, -5, -1, 0 );
			ac = new AddonComponent( 1996 );
			AddComponent( ac, -5, 0, 0 );
			ac = new AddonComponent( 1995 );
			AddComponent( ac, -5, 1, 0 );
			ac = new AddonComponent( 1996 );
			AddComponent( ac, -5, 2, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, -4, -2, 0 );
			ac = new AddonComponent( 1996 );
			AddComponent( ac, -4, -1, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, -4, 0, 0 );
			ac = new AddonComponent( 1993 );
			AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 1995 );
			AddComponent( ac, -4, 2, 0 );
			ac = new AddonComponent( 1995 );
			AddComponent( ac, -4, 3, 0 );
			ac = new AddonComponent( 1993 );
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 1995 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 1993 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 1995 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 1995 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 1993 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 1993 );
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 1996 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 1995 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1995 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 1995 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 1993 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 1996 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1996 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1995 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 1996 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1995 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1993 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 1996 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 1993 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1993 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 1995 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 1995 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 1993 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 1996 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 1996 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 1993 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 1993 );
			AddComponent( ac, 6, -2, 0 );
			ac = new AddonComponent( 1996 );
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 1993 );
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 1993 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 1996 );
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 1996 );
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 1995 );
			AddComponent( ac, 5, -2, 0 );
			ac = new AddonComponent( 1995 );
			AddComponent( ac, 5, -1, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, 5, 0, 0 );
			ac = new AddonComponent( 1996 );
			AddComponent( ac, 5, 1, 0 );
			ac = new AddonComponent( 1993 );
			AddComponent( ac, 5, 2, 0 );
			ac = new AddonComponent( 1995 );
			AddComponent( ac, 5, 3, 0 );
			ac = new AddonComponent( 1994 );
			AddComponent( ac, 6, -1, 0 );
			ac = new AddonComponent( 1996 );
			AddComponent( ac, 6, 0, 0 );
			ac = new AddonComponent( 1995 );
			AddComponent( ac, 6, 1, 0 );
			ac = new AddonComponent( 1993 );
			AddComponent( ac, 6, 2, 0 );
			ac = new AddonComponent( 1993 );
			AddComponent( ac, 6, 3, 0 );

		}

		public AG_RivergatesGateAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_RivergatesGateAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_RivergatesGateAddon();
			}
		}

		[Constructable]
		public AG_RivergatesGateAddonDeed()
		{
			Name = "AG_RivergatesGate";
		}

		public AG_RivergatesGateAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}