/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_RymalielMillAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_RymalielMillAddonDeed();
			}
		}

		[ Constructable ]
		public AG_RymalielMillAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 1994 );
			ac.Hue = 2796;
			AddComponent( ac, 0, 0, 17 );
			ac = new AddonComponent( 2210 );
			ac.Hue = 2796;
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 7835 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 2002 );
			ac.Hue = 2796;
			ac.Name = "Crane Support";
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 1996 );
			ac.Hue = 2796;
			AddComponent( ac, -1, 0, 17 );
			ac = new AddonComponent( 322 );
			ac.Hue = 2796;
			AddComponent( ac, 1, -1, 15 );
			ac = new AddonComponent( 2002 );
			ac.Hue = 2796;
			ac.Name = "Crane Support";
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 7852 );
			ac.Hue = 2995;
			AddComponent( ac, 0, 0, 17 );
			ac = new AddonComponent( 322 );
			ac.Hue = 2796;
			AddComponent( ac, 0, 0, 15 );
			ac = new AddonComponent( 322 );
			ac.Hue = 2796;
			AddComponent( ac, 0, -1, 15 );
			ac = new AddonComponent( 322 );
			ac.Hue = 2796;
			AddComponent( ac, 2, -1, 15 );
			ac = new AddonComponent( 321 );
			ac.Hue = 2796;
			AddComponent( ac, 2, 0, 15 );
			ac = new AddonComponent( 3530 );
			ac.Hue = 2947;
			AddComponent( ac, 1, 0, 15 );
			ac = new AddonComponent( 3530 );
			ac.Hue = 2947;
			AddComponent( ac, 2, 0, 15 );
			ac = new AddonComponent( 7836 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 321 );
			ac.Hue = 2796;
			AddComponent( ac, 1, 0, 15 );

		}

		public AG_RymalielMillAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_RymalielMillAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_RymalielMillAddon();
			}
		}

		[Constructable]
		public AG_RymalielMillAddonDeed()
		{
			Name = "AG_RymalielMill";
		}

		public AG_RymalielMillAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}