/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_SampleElevatorAddonAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_SampleElevatorAddonAddonDeed();
			}
		}

		[ Constructable ]
		public AG_SampleElevatorAddonAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 38 );
			ac.Hue = 2713;
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 38 );
			ac.Hue = 2713;
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 38 );
			ac.Hue = 2713;
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 38 );
			ac.Hue = 2713;
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 37 );
			ac.Hue = 2713;
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 37 );
			ac.Hue = 2713;
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 37 );
			ac.Hue = 2713;
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 37 );
			ac.Hue = 2713;
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 37 );
			ac.Hue = 2713;
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 37 );
			ac.Hue = 2713;
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 37 );
			ac.Hue = 2713;
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 42 );
			ac.Hue = 2713;
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 41 );
			ac.Hue = 2713;
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 43 );
			ac.Hue = 2713;
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 44 );
			ac.Hue = 2713;
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 44 );
			ac.Hue = 2713;
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 43 );
			ac.Hue = 2713;
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 37 );
			ac.Hue = 2713;
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 40 );
			ac.Hue = 2713;
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 1308 );
			ac.Hue = 2713;
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 1305 );
			ac.Hue = 2713;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1310 );
			ac.Hue = 2713;
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1309 );
			ac.Hue = 2713;
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 1309 );
			ac.Hue = 2713;
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1307 );
			ac.Hue = 2713;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1308 );
			ac.Hue = 2713;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2713;
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 1310 );
			ac.Hue = 2713;
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1308 );
			ac.Hue = 2713;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2713;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1309 );
			ac.Hue = 2713;
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 1308 );
			ac.Hue = 2713;
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 1305 );
			ac.Hue = 2713;
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1307 );
			ac.Hue = 2713;
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1305 );
			ac.Hue = 2713;
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 1307 );
			ac.Hue = 2713;
			AddComponent( ac, -1, -1, 20 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2713;
			AddComponent( ac, -1, 0, 20 );
			ac = new AddonComponent( 1305 );
			ac.Hue = 2713;
			AddComponent( ac, -1, 1, 20 );
			ac = new AddonComponent( 1307 );
			ac.Hue = 2713;
			AddComponent( ac, -1, 2, 20 );
			ac = new AddonComponent( 1309 );
			ac.Hue = 2713;
			AddComponent( ac, 0, -1, 20 );
			ac = new AddonComponent( 1307 );
			ac.Hue = 2713;
			AddComponent( ac, 0, 0, 20 );
			ac = new AddonComponent( 1306 );
			ac.Hue = 2713;
			AddComponent( ac, 0, 1, 20 );
			ac = new AddonComponent( 1307 );
			ac.Hue = 2713;
			AddComponent( ac, 0, 2, 20 );
			ac = new AddonComponent( 1306 );
			ac.Hue = 2713;
			AddComponent( ac, 1, -1, 20 );
			ac = new AddonComponent( 1310 );
			ac.Hue = 2713;
			AddComponent( ac, 1, 0, 20 );
			ac = new AddonComponent( 1310 );
			ac.Hue = 2713;
			AddComponent( ac, 1, 1, 20 );
			ac = new AddonComponent( 1309 );
			ac.Hue = 2713;
			AddComponent( ac, 1, 2, 20 );
			ac = new AddonComponent( 1308 );
			ac.Hue = 2713;
			AddComponent( ac, 2, -1, 20 );
			ac = new AddonComponent( 1311 );
			ac.Hue = 2713;
			AddComponent( ac, 2, 0, 20 );
			ac = new AddonComponent( 1307 );
			ac.Hue = 2713;
			AddComponent( ac, 2, 1, 20 );
			ac = new AddonComponent( 1307 );
			ac.Hue = 2713;
			AddComponent( ac, 2, 2, 20 );
			ac = new AddonComponent( 1872 );
			ac.Hue = 2713;
			AddComponent( ac, 0, 0, 20 );
			ac = new AddonComponent( 1872 );
			ac.Hue = 2713;
			AddComponent( ac, 0, 1, 20 );
			ac = new AddonComponent( 1872 );
			ac.Hue = 2713;
			AddComponent( ac, 1, 0, 20 );
			ac = new AddonComponent( 1872 );
			ac.Hue = 2713;
			AddComponent( ac, 1, 1, 20 );
			ac = new AddonComponent( 1877 );
			ac.Hue = 2713;
			AddComponent( ac, -1, -1, 20 );
			ac = new AddonComponent( 1878 );
			ac.Hue = 2713;
			AddComponent( ac, 2, 2, 20 );
			ac = new AddonComponent( 1879 );
			ac.Hue = 2713;
			AddComponent( ac, 2, -1, 20 );
			ac = new AddonComponent( 1880 );
			ac.Hue = 2713;
			AddComponent( ac, -1, 2, 20 );
			ac = new AddonComponent( 1876 );
			ac.Hue = 2713;
			AddComponent( ac, -1, 0, 20 );
			ac = new AddonComponent( 1876 );
			ac.Hue = 2713;
			AddComponent( ac, -1, 1, 20 );
			ac = new AddonComponent( 1875 );
			ac.Hue = 2713;
			AddComponent( ac, 0, -1, 20 );
			ac = new AddonComponent( 1875 );
			ac.Hue = 2713;
			AddComponent( ac, 1, -1, 20 );
			ac = new AddonComponent( 1874 );
			ac.Hue = 2713;
			AddComponent( ac, 2, 0, 20 );
			ac = new AddonComponent( 1874 );
			ac.Hue = 2713;
			AddComponent( ac, 2, 1, 20 );
			ac = new AddonComponent( 1873 );
			ac.Hue = 2713;
			AddComponent( ac, 0, 2, 20 );
			ac = new AddonComponent( 1873 );
			ac.Hue = 2713;
			AddComponent( ac, 1, 2, 20 );
			ac = new AddonComponent( 29 );
			ac.Hue = 2713;
			AddComponent( ac, -2, -2, 0 );

		}

		public AG_SampleElevatorAddonAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_SampleElevatorAddonAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_SampleElevatorAddonAddon();
			}
		}

		[Constructable]
		public AG_SampleElevatorAddonAddonDeed()
		{
			Name = "AG_SampleElevatorAddon";
		}

		public AG_SampleElevatorAddonAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}
