/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_YuanTiElevatorAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_YuanTiElevatorAddonDeed();
			}
		}

		[ Constructable ]
		public AG_YuanTiElevatorAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, -1, 5 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 0, 5 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 1, 5 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 2, 5 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, -1, 5 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 0, 5 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 1, 5 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 2, 5 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, -1, 5 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 0, 5 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 1, 5 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 2, 5 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, -1, 5 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 0, 5 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 1, 5 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 2, 5 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, -1, 10 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 0, 10 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 1, 10 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 2, 10 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, -1, 10 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 0, 10 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 1, 10 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 2, 10 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, -1, 10 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 0, 10 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 1, 10 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 2, 10 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, -1, 10 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 0, 10 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 1, 10 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 2, 10 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, -1, 15 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 0, 15 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 1, 15 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 2, 15 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, -1, 15 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 0, 15 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 1, 15 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 2, 15 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, -1, 15 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 0, 15 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 1, 15 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 2, 15 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, -1, 15 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 0, 15 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 1, 15 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 2, 15 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, -1, 20 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 0, 20 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 1, 20 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 2, 20 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, -1, 20 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 0, 20 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 1, 20 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 2, 20 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, -1, 20 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 0, 20 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 1, 20 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 2, 20 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, -1, 20 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 0, 20 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 1, 20 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 2, 20 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, -1, 25 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 0, 25 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 1, 25 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 2, 25 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, -1, 25 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 0, 25 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 1, 25 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 2, 25 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, -1, 25 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 0, 25 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 1, 25 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 2, 25 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, -1, 25 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 0, 25 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 1, 25 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 2, 25 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, -1, 30 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 0, 30 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 1, 30 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 2, 30 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, -1, 30 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 0, 30 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 1, 30 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 2, 30 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, -1, 30 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 0, 30 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 1, 30 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 2, 30 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, -1, 30 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 0, 30 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 1, 30 );
			ac = new AddonComponent( 1822 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 2, 30 );
			ac = new AddonComponent( 6173 );
			ac.Hue = 1439;
			AddComponent( ac, -1, -1, 35 );
			ac = new AddonComponent( 6174 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 0, 35 );
			ac = new AddonComponent( 6175 );
			ac.Hue = 1439;
			AddComponent( ac, 0, -1, 35 );
			ac = new AddonComponent( 6176 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 0, 35 );
			ac = new AddonComponent( 6177 );
			ac.Hue = 1439;
			AddComponent( ac, 1, -1, 35 );
			ac = new AddonComponent( 6178 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 0, 35 );
			ac = new AddonComponent( 6179 );
			ac.Hue = 1439;
			AddComponent( ac, 2, -1, 35 );
			ac = new AddonComponent( 6180 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 0, 35 );
			ac = new AddonComponent( 6181 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 1, 35 );
			ac = new AddonComponent( 6182 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 1, 35 );
			ac = new AddonComponent( 6183 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 1, 35 );
			ac = new AddonComponent( 6184 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 1, 35 );
			ac = new AddonComponent( 6176 );
			ac.Hue = 1439;
			AddComponent( ac, 1, 2, 35 );
			ac = new AddonComponent( 6179 );
			ac.Hue = 1439;
			AddComponent( ac, -1, 2, 35 );
			ac = new AddonComponent( 6174 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 2, 35 );
			ac = new AddonComponent( 6175 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 2, 35 );

		}

		public AG_YuanTiElevatorAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_YuanTiElevatorAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_YuanTiElevatorAddon();
			}
		}

		[Constructable]
		public AG_YuanTiElevatorAddonDeed()
		{
			Name = "AG_YuanTiElevator";
		}

		public AG_YuanTiElevatorAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}
